#cloud-config
users:
  - name: ubuntu #benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL #sudo regeln für den benutzer "ubuntu"
    groups: users, admin #gruppen, in denen der benutzer "ubuntu" ist
    home: /home/ubuntu #heim-verzeichnis des benutzer "ubuntu"
    shell: /bin/bash #verzeichnis von bash
    ssh_authorized_keys: #fuegt keys zur datei "authorized keys" des benutzers hinzu, optional
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key       
ssh_pwauth: false #wenn "true", sshd wird so konfiguriert, dass das passwort login akzeptiert wird
disable_root: false #wenn "true", root login wird ausgeschaltet, wenn "false", eingeschaltet
package_update: true #wenn "true", wendet updates von packages an
packages: #installierte packages
  - curl #curl wird verwendet, um daten von einem server zu empfangen und zu senden
  - wget #get wird verwendet, um daten von web server herunterzuladen
